# Generated by Django 4.2.5 on 2023-09-28 05:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default=None, null=True),
        ),
    ]
